package tebd_atividade_1.entity;
// Generated 15/08/2017 17:13:13 by Hibernate Tools 4.3.1


import java.util.Collection;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private int id;
     private String descricao;
     private Collection items = new HashSet(0);

    public Pedido() {
    }
	
    public Pedido(int id, String descricao) {
        this.id = id;
        this.descricao = descricao;
    }
    
    public Pedido(int id, String descricao, Set items) {
       this.id = id;
       this.descricao = descricao;
       this.items = items;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Collection getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }

    public void addItem(String descricao, int quantidade, double valor) {
        this.items.add(new Item(descricao, quantidade, valor));
    }

    public double getValorTotalPedido() {
        Iterator it = this.items.iterator();
        double total = 0;
        while (it.hasNext()) {
            total += ((Item) it.next()).getValorTotalItem();
        }
        return total;
    }

    public String toString() {
        String retorno;
        int count = 1;
        retorno = "Pedido:\n";
        retorno += "Id do Pedido:" + this.id + "\n";
        retorno += "Descricao do Pedido: " + this.descricao + "\n";
        retorno += "Total do Pedido: " + this.getValorTotalPedido() + "\n";
        retorno += "Itens Comprados: \n";
        Iterator it = this.items.iterator();
        while (it.hasNext()) {
            retorno += count + ": " + it.next().toString() + "\n";
            count++;
        }
        retorno += "-------------------------";
        return retorno;
    }

}


